"""empty message

Revision ID: a9e10de97e71
Revises: 1e75308f73be
Create Date: 2026-02-18 00:24:36.244351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e10de97e71'
down_revision: Union[str, Sequence[str], None] = '1e75308f73be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('room', 'room_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('busy', 'booked', 'free', name='roomstatuschoices'),
               existing_nullable=False)
    op.drop_constraint(op.f('room_room_status_key'), 'room', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('room_room_status_key'), 'room', ['room_status'], postgresql_nulls_not_distinct=False)
    op.alter_column('room', 'room_status',
               existing_type=sa.Enum('busy', 'booked', 'free', name='roomstatuschoices'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('booking', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
